CREATE DATABASE Fiel
CHARACTER SET utf8mb4
COLLATE utf8mb4_unicode_ci;

USE Fiel;

CREATE TABLE address_names (
    ana_id BIGINT AUTO_INCREMENT PRIMARY KEY,
    ana_name VARCHAR(255) NOT NULL,
    ana_add_id BIGINT NOT NULL,
    ana_createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ana_updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    ana_publishedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE addresses (
    add_id BIGINT AUTO_INCREMENT PRIMARY KEY,
    add_number INT NOT NULL,
    add_complement VARCHAR(255),
    add_createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    add_updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    add_publishedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    add_rty_id BIGINT NOT NULL,
    add_cit_id BIGINT NOT NULL,
    add_str_id BIGINT NOT NULL
);

CREATE TABLE cards (
    car_id BIGINT AUTO_INCREMENT PRIMARY KEY,
    car_usr_id BIGINT NOT NULL,
    car_principal TINYINT(1) NOT NULL,
    car_number VARCHAR(20) NOT NULL,
    car_ccv VARCHAR(10) NOT NULL,
    car_holder VARCHAR(255) NOT NULL,
    car_valid DATE NOT NULL,
    car_createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    car_updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    car_publishedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    car_pty_id BIGINT NOT NULL
);

CREATE TABLE cities (
    cit_id BIGINT AUTO_INCREMENT PRIMARY KEY,
    cit_city VARCHAR(255) NOT NULL,
    cit_createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    cit_updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    cit_publishedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    cit_sta_id BIGINT NOT NULL
);

CREATE TABLE countries (
    cou_id BIGINT AUTO_INCREMENT PRIMARY KEY,
    cou_country VARCHAR(255),
    cou_createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    cou_updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    cou_publishedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE genders (
    gen_id BIGINT AUTO_INCREMENT PRIMARY KEY,
    gen_name VARCHAR(50) NOT NULL
);

CREATE TABLE payment_types (
    pty_id BIGINT AUTO_INCREMENT PRIMARY KEY,
    pty_name VARCHAR(100) NOT NULL,
    pty_createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    pty_updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    pty_publishedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE residence_types (
    rty_id BIGINT AUTO_INCREMENT PRIMARY KEY,
    rty_name VARCHAR(100) NOT NULL,
    rty_createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    rty_updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    rty_publishedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE states (
    sta_id BIGINT AUTO_INCREMENT PRIMARY KEY,
    sta_state VARCHAR(255) NOT NULL,
    sta_uf VARCHAR(10) NOT NULL,
    sta_cou_id BIGINT NOT NULL,
    sta_createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    sta_updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    sta_publishedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE street_types (
    sty_id BIGINT AUTO_INCREMENT PRIMARY KEY,
    sty_name VARCHAR(100) NOT NULL,
    sty_createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    sty_updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    sty_publishedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE streets (
    str_id BIGINT AUTO_INCREMENT PRIMARY KEY,
    str_street VARCHAR(255) NOT NULL,
    str_neighborhood VARCHAR(255) NOT NULL,
    str_zip VARCHAR(20) NOT NULL,
    str_sty_id BIGINT NOT NULL,
    str_createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    str_updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    str_publishedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE users (
    usr_id BIGINT AUTO_INCREMENT PRIMARY KEY,
    usr_name VARCHAR(255) NOT NULL,
    usr_password VARCHAR(255) NOT NULL,
    usr_active TINYINT(1) NOT NULL DEFAULT 1,
    usr_gen_id BIGINT NOT NULL,
    usr_birthday DATE NOT NULL,
    usr_cpf VARCHAR(20) NOT NULL,
    usr_phone_number VARCHAR(20) NOT NULL,
    usr_createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    usr_updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    usr_publishedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE users_addresses (
    uad_usr_id BIGINT NOT NULL,
    uad_ana_id BIGINT NOT NULL,
    udd_publishedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    udd_createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    udd_updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (uad_ana_id, uad_usr_id)
);

-- Foreign Keys
ALTER TABLE address_names ADD CONSTRAINT fk_address_names_addresses FOREIGN KEY (ana_add_id) REFERENCES addresses (add_id);
ALTER TABLE addresses ADD CONSTRAINT fk_addresses_cities FOREIGN KEY (add_cit_id) REFERENCES cities (cit_id);
ALTER TABLE addresses ADD CONSTRAINT fk_addresses_residence_types FOREIGN KEY (add_rty_id) REFERENCES residence_types (rty_id);
ALTER TABLE addresses ADD CONSTRAINT fk_addresses_streets FOREIGN KEY (add_str_id) REFERENCES streets (str_id);
ALTER TABLE cards ADD CONSTRAINT fk_cards_payment_types FOREIGN KEY (car_pty_id) REFERENCES payment_types (pty_id);
ALTER TABLE cards ADD CONSTRAINT fk_cards_users FOREIGN KEY (car_usr_id) REFERENCES users (usr_id);
ALTER TABLE cities ADD CONSTRAINT fk_cities_states FOREIGN KEY (cit_sta_id) REFERENCES states (sta_id);
ALTER TABLE states ADD CONSTRAINT fk_states_countries FOREIGN KEY (sta_cou_id) REFERENCES countries (cou_id);
ALTER TABLE streets ADD CONSTRAINT fk_streets_street_types FOREIGN KEY (str_sty_id) REFERENCES street_types (sty_id);
ALTER TABLE users_addresses ADD CONSTRAINT fk_users_addresses_address_names FOREIGN KEY (uad_ana_id) REFERENCES address_names (ana_id);
ALTER TABLE users_addresses ADD CONSTRAINT fk_users_addresses_users FOREIGN KEY (uad_usr_id) REFERENCES users (usr_id);
ALTER TABLE users ADD CONSTRAINT fk_users_genders FOREIGN KEY (usr_gen_id) REFERENCES genders (gen_id);
