import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/header";
import Footer from "@/components/footer";
import { GlobalProvider } from "@/context/GlobalContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="app">
        <GlobalProvider>
          <Header />
          <main className="content">{children}</main>
          <Footer />
        </GlobalProvider>
      </body>
    </html>
  );
}
