import ChatIA from "@/components/chatIA";
import Footer from "@/components/footer";
import Header from "@/components/header";
import { GlobalProvider } from "@/context/GlobalContext";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="app">
        <ChatIA />
        
        <GlobalProvider>
          <Header />
            <main className="content">{children}</main>
          <Footer />
        </GlobalProvider>
      </body>
    </html>
  );
}
